{{- if and .Values.vastApiKey.create .Values.vastApiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vastai-operator.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vastai-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.vastApiKey.key }}: {{ .Values.vastApiKey.value | quote }}
{{- end }}
